### PR TITLE
Add support for tab in/outdenting lists

### PR DESCRIPTION
**Pull request by qrush**
Commented it up a bunch too!

### CODE REVIEW

**Comment by qrush** [comment]
Hey there, any movement on this? Anything I can help to get it in?

**Comment by mdespuits** [comment]
:+1: Definitely a big request for users at my company.

**Comment by tiff** [comment]
Hey, I'll have a look at the code and test across browsers whether it creates any unwanted html markup. Thanks! Sorry for the late reply.

**Comment by qrush** [comment]
Added some more configuration in this latest commit. Changing `indentMatcher` to `/.*/` will allow indenting on any element. Also, hitting Backspace when at the start of a blockquote will now outdent.

**Comment by tiff** [comment]
Thanks so much! Just fyi: I still have this on my list. I'm quite busy right now but I'm working on getting wysihtml5 v0.3 stable out with its own little website (gh-pages). I'll make sure that indent/outdent will be part of wysihtml5 v0.4.

**Comment by qrush** [comment]
What's your ETA on that? I have another slew of patches based on top of these as well...I'd rather not keep our modifications in a fork long-term.

**Comment by qrush** [comment]
What I'm talking about: https://github.com/qrush/wysihtml5/compare/tab-indent...show-hide-dialog-config

**Comment by tiff** [comment]
ETA for 0.3: This weekend

ETA for 0.4: Hopefully within the next 2 months

**Comment by qrush** [comment]
Not happy at all with this, didn't end up using it. The list in/outdent behavior is extremely erratic and random, can't nail down why yet. Closing this.

**Comment by mdespuits** [comment]
Any chance that this could still be added? This is a huge feature request from users at my company (they used it extensively when using a previous editor), so it would be most appreciated.

The only option this would give us at the moment is to build our own custom installation, which ultimately would just be an inconvenience, but it would be nice to have. Thanks for the attempt @qrush.

**Comment by tiff** [comment]
I'm spending some time now on this. I also wanna make this behave more intuitive: If the user enters a "\* " or a "1. " at the beginning of an line a list should automatically be created.

**Comment by farfalena-zz** [comment]
First of all I would like to thank you for this library. It is very lightweight, ease to integrate and produces clean html.

I am sorry if I am missing something, but what is the status of this issue? Will nested lists (indentation in and out) be supported by release 0.4, and if yes, when is this version expected?

If release 0.4 is not expected soon, is there a branch I could use that implements this functionality.

Many thanks in advance for your support.

**Comment by Santas** [comment]
What is the status of this issue? Thank you

**Comment by nadimkobeissi** [comment]
Bump!

**Comment by feross** [comment]
Bump

**Comment by jakobdamjensen** [comment]
Bump

**Comment by thapar** [comment]
Bump

**Pull request closed without merging**
