### PR TITLE
Allow functions as check_attributes rules

### PR DESCRIPTION
**Pull request by p3drosola**
This allows rules to be specified as functions, so you can easily add logic into the rules, without having to patch the wysihtml5 core.

for example this rule only allows the `color` attribute of a `h1` to be `green` if it's `id` is `main`.

The second rule adds a `target='_self'` if the link points to your website and `target='_blank'` if not

```
"h1": {
  "check_attributes": {
    "color" : function(val, oldNode) {
      if (val === 'green' && oldNode.id === 'main') return val;
    }
  }
},
"a" : {
  "check_attributes": {
    "target" : function(val, oldNode) {
      if (oldNode.href.match(/^http:\/\/mysite\.com/)) return '_self';
      return '_blank';
    }
  }
}
```

The example is pretty silly, but it can be quite powerful.

This approach could also be applied to other types of rules.

:+1: It's completely backwards compatible, and passes the test suite.

### CODE REVIEW

**Comment by Mipme** [comment]
Hey Pedro - isn't this also possible your https://github.com/xing/wysihtml5/pull/166 request? Since you have a function already executed on a tag type i could also manipulate the attributes. The only question here is if wysihtml5 will validate the attributes after the function again and then blow it...

**Comment by p3drosola** [comment]
bump. 

@tiff any thoughts on the matter?

**Comment by Mipme** [comment]
Just bumped into a kind-of-issue:

For instance i'm adding to all non-local urls a rel="nofollow" and target="_blank".
Everything works fine with either your implementation or mine except for creating links with the dialog in toolbar.
Then the parser is not called and no manipulation of the a-tag happens.

We should take care of this as well, ain't?

**Comment by tiff** [comment]
@Mipme The parser is not invoked when you insert a link via the toolbar. But it will be invoked right before the content gets submitted to the server. Your desired attributes will be added then. Can you confirm?

**Comment by Mipme** [comment]
@tiff I can confirm that. In my case i have a autosave function that sends the content of the editor to the server every minute if something has changed. I'm using editor.getValue(true) - then everything is like you describe. Using editor.getValue(false) returns the code without tag manipulation.

I guess this is intented to be as such... So, my bad.

Questions regarding the parser:
- On the server i'm using htmlpurify with tidy. So i'd like my autosave to set the code in the editor to the server-cleaned response. I tried to do this with editor.setValue, but i kept loosing the focus. At the moment i worked around this by only updating the editor content if it has NO focus. Any ideas on that? 
- can i turn it of when pasting into textarea while working on the html-code?

Thx!

**Comment by micho** [comment]
Bump

**Comment by p3drosola** [comment]
closing because I've kept adding other stuff to the repo, that shouldn't be in the same pull req.

**Pull request closed without merging**
