### PR TITLE
Pretty please add a deprecation notice

### PR DESCRIPTION
**Pull request by dandv**
Thousands of people land here, but the project is no longer developed.

### CODE REVIEW

**Comment by pduersteler** [comment]
+1

link to a repo that is up to date

**Comment by thachvearak** [comment]
fdsafsaf

**Comment by thachvearak** [comment]
how can i use this project ? wysihtml5

**Comment by dandv** [comment]
The project fork is now maintained at https://github.com/Voog/wysihtml

**Pull request closed without merging**
