### PR TITLE
Fixed relative URL validation [Closes #216, #25, #3]

### LINKED ISSUE #216: Attributes are removed in HTML code
A number of attributes of elements are removed by WYSIHTML5. 

For example, if the folllowing code is pasted in:

``` html
<div id="my-named-div">...</div>
```

It is turned into a plain div element with no ID.

Also, I added an anchor link with a mailto address:

``` html
<a href="mailto:someone@website.com">Email me</a>
```

The entire href attribute was removed from this.

Can anyone help with this?

### PR DESCRIPTION
**Pull request by hrach**

### CODE REVIEW

**Comment by hrach** [comment]
ping @tiff :)

**Comment by tiff** [comment]
pong @hrach. :)

In general this makes absolutely sense.

However I haven't merged this yet since I'm considering a different and a more simple approach on how to parse and convert attributes. Basically I wanna get rid of those parser methods (href, src, ...) and move the logic to the parser rule set (eg. advanced.js) where the user can define regular expressions or functions for handling attributes.

**Comment by hrach** [comment]
Well, I get the point about some refactoring thing, but from my point of view you should [release more often](http://en.wikipedia.org/wiki/Release_early,_release_often) ;) It could be part of another version.

**Comment by TomorrowToday** [comment]
Merge code that works today, then build the next great thing.

**Comment by 3mpire** [comment]
I vote for merging as well this is a fix that I would like to be able to use :)

**Comment by virgofx** [comment]
@tiff - Any news on the progress on relative URLs?

I find relative URLs a necessity for my project as well. I have merged this pull request into my local branch for immediate needs and have additionally identified a few more bugs not fixed via the current change set of this pull request. (Specifically revisiting existing relative links within the composer will cause the interpolate to fire when opening a dialog).

**Comment by fxck** [comment]
@tiff any news?

**Comment by rayrigam** [comment]
I need this as well... Unfortunately, I would have to install node.js to be able to compile the minimized js file to include this commit in the latest wysihtml5. Is that correct? @tiff , any updates on including this on the master? In my case, it's easy to check on the server side for the validity of internal relative urls before saving them to the database, so I see no risk to implement this.

**Pull request closed without merging**
